package com.example.powerbi_edu_backend.Model.config;

import com.example.powerbi_edu_backend.Model.Entities.*;
import com.example.powerbi_edu_backend.Repository.*;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.time.LocalDateTime;
import java.util.List;


@Component
public class InitialDataInsert {
    private final NewsRepository newsRepository;
    private final DocumentationsRepository documentationsRepository;

    private final CourseRepository courseRepository;
    private final LearningPathRepository learningPathRepository;
    private final QuestionRepository questionRepository;

    private final ExamRepository examRepository;


    public InitialDataInsert(NewsRepository newsRepository, DocumentationsRepository documentationsRepository, CourseRepository courseRepository, LearningPathRepository learningPathRepository, QuestionRepository questionRepository, ExamRepository examRepository) {
        this.newsRepository = newsRepository;
        this.documentationsRepository = documentationsRepository;
        this.courseRepository = courseRepository;
        this.learningPathRepository = learningPathRepository;
        this.questionRepository = questionRepository;
        this.examRepository = examRepository;
    }

    @PostConstruct
    public void initData()
    {
        this.newsRepository.save(new News("Power BI July 2022 Feature Summary", "PowerBI Mobile", LocalDateTime.of(2022, 7, 14, 5,5,5), "Welcome to the July 2022 update. We are thrilled to announce the Error Bars general availability, Metric visuals and Datamarts updates, query performance and data hub improvements, Data in space augmented reality new mobile feature, accessibility enhancements for embedded reports. There is more to explore, please continue to read on.", List.of("Announcements", "Features"),"https://powerbi.microsoft.com/en-us/blog/power-bi-july-2022-feature-summary/"));
        this.newsRepository.save(new News("“Data in space” in preview: Now Power BI can be truly everywhere", "PowerBI Mobile", LocalDateTime.of(2022, 7, 6, 5,5,5), "We live in a connected world and almost everything around us generates data. Data in Space is new feature that uses augmented reality to create persistent spatial anchors in the real world and attach Power BI content to those anchors. Data in space connects your business data to your real-world scenarios in facility management, manufacturing, retail and many more, and now employees can easily discover and use it for better, and more informed decisions.",List.of("Announcements", "Data loss prevention"), "https://powerbi.microsoft.com/en-us/blog/data-in-space-in-preview-now-power-bi-can-be-truly-everywhere/"));
        this.newsRepository.save(new News("Analyzing your Microsoft Exchange Account Data with Power Query", "PowerBI Desktop", LocalDateTime.of(2021, 1, 9, 5,5,5), "One of the interesting additions to the Power Query Preview December update is the ability to import data from Microsoft Exchange. In this blog post, Miguel Llopis (a Program Manager in the Power Query team) will walk us through the capabilities exposed by this new feature and show how you can easily do analytics on top of your Exchange account.", List.of("Analysis Services"), "https://powerbi.microsoft.com/en-us/blog/analyzing-your-microsoft-exchange-account-data-with-power-query/"));
        this.newsRepository.save(new News("Happy Holidays with Power BI Mobile, Part 2: Tracking Santa with Power Map", "PowerBI Mobile", LocalDateTime.of(2021, 12, 25, 5,5,5), "Following up on our Holiday post last week, we wanted to track Santa using Power Map!In this video you can find Santa’s official NORAD route around the world with more insights about some destinations and visitors to the official NORAD Santa Tracker.", List.of("Announcements", "Developers"), "https://powerbi.microsoft.com/en-us/blog/happy-holidays-with-power-bi-part-2-tracking-santa-with-power-map/"));
        this.newsRepository.save(new News("Updates to Microsoft Purview data loss prevention policies in Power BI Desktop", "PowerBI Desktop", LocalDateTime.of(2022, 8, 22, 5,5,5), "Data loss prevention (DLP) policies help you govern the sensitive information managed in your Power BI tenant and comply with governmental or industry regulations, such as GDPR (the European Union’s General Data Protection Regulation). Earlier this year, we announced the release of DLP policies for Power BI to public preview. We’re happy to share with you two significant enhancements to DLP policies in Power BI: CPU metering for DLP policy evaluation, ability to override DLP policy tips and option to report of a false positive detection.", List.of("Developers", "Features", "Analysis Services"),"https://powerbi.microsoft.com/en-us/blog/updates-to-microsoft-purview-data-loss-prevention-policies-in-power-bi/"));
        this.newsRepository.save(new News("Join us! 18-23 September 2022. The FIRST ever Microsoft Power Platform Conference!", "PowerBI Desktop", LocalDateTime.of(2022, 8, 8, 5,5,5), "The first annual Power Platform Conference sponsored by Microsoft and Power Platform Conference is coming to Orlando for an amazing in-person event this September, with keynotes, sessions, breakouts and more! All dedicated to Microsoft Power Platform products: Power BI, Power Automate, Power Apps, Power Pages, and Power Virtual Agents.", List.of("Developers", "Information Protection"), "https://powerbi.microsoft.com/en-us/blog/join-us-september-18-23-for-the-first-ever-microsoft-power-platform-conference/"));
        this.newsRepository.save(new News("Analysis Services server properties in Power BI Premium are now in public preview", "PowerBI Service", LocalDateTime.of(2022, 8, 2, 5,5,5), "At Power BI, we’ve committed to providing powerful enterprise modeling capabilities to Power BI Premium. As part of our product journey over the past five years, this commitment has brought numerous Azure Analysis Services (AAS) semantic modeling features for performance and management to Power BI Premium.", List.of("Announcements", "Report Server"), "https://powerbi.microsoft.com/en-us/blog/analysis-services-server-properties-in-power-bi-premium-are-now-in-public-preview/"));
        this.newsRepository.save(new News("ExecuteQueries REST API versus XMLA endpoints at scale", "PowerBI Service", LocalDateTime.of(2022, 7, 18, 5,5,5), "Power BI APIs can support you at any scale, but there is no one-size-fits-all API. The ExecuteQueries API is a great choice at small scale. For large-scale solutions, switch to XMLA endpoints and host your datasets on Power BI Premium.", List.of("Announcements", "API", "Features"), "https://powerbi.microsoft.com/en-us/blog/executequeries-rest-api-versus-xmla-endpoints-at-scale/"));
        this.newsRepository.save(new News("Power BI paves the way for smooth Azure Analysis Services migrations", "PowerBI Service", LocalDateTime.of(2022, 8, 16, 5,5,5), "We are committed to helping our Azure Analysis Services customers unlock the enormous capabilities of Power BI as a superset of Azure Analysis Services through a smooth migration path to Power BI. As part of this effort, we are happy to announce today that Power BI has reached yet another compatibility milestone with the introduction of explicit Dataset Write permissions.", List.of("Announcements", "Goals"), "https://powerbi.microsoft.com/en-us/blog/power-bi-paves-the-way-for-smooth-azure-analysis-services-migrations/"));

        this.documentationsRepository.save(new Documentations("What is Power BI - Desktop?", "PowerBI Desktop", List.of("What is Power BI?---https://docs.microsoft.com/en-us/power-bi/fundamentals/power-bi-overview", "What is Power BI Desktop?---https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-what-is-desktop","Power BI videos---https://docs.microsoft.com/en-us/power-bi/fundamentals/videos", "What's new in Power BI?---https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop", "Sign up for Power BI---https://docs.microsoft.com/en-us/power-bi/fundamentals/service-self-service-signup-for-power-bi"), "Overview"));
        this.documentationsRepository.save(new Documentations("Get started with Power BI - Desktop?", "PowerBI Desktop", List.of("Create and use analytics reports---https://docs.microsoft.com/en-us/learn/paths/create-use-analytics-reports-power-bi/", "Get data with Power BI Desktop---https://docs.microsoft.com/en-us/learn/modules/get-data-power-bi/?tutorial-step=1"), "Learn"));
        this.documentationsRepository.save(new Documentations("Power BI documentation business users", "PowerBI Desktop", List.of("What is a Power BI business user?---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-consumer", "Take a tour of the Power BI service---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reading-view", "Review concepts and content---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts"), "Overview"));
        this.documentationsRepository.save(new Documentations("Get started with Power BI for business users", "PowerBI Desktop", List.of("Learn about reports---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reports", "Learn about dashboards---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-dashboards", "View a report---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-report-view", "Use report filters---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-report-filter"), "Learn"));
        this.documentationsRepository.save(new Documentations("Connect to data", "PowerBI Desktop", List.of("What is a Power BI business user?---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-consumer", "Take a tour of the Power BI service---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reading-view", "Review concepts and content---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts"), "Overview"));
        this.documentationsRepository.save(new Documentations("Develop in Power BI - Desktop", "PowerBI Desktop", List.of("What is a Power BI business user?---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-consumer", "Take a tour of the Power BI service---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reading-view", "Review concepts and content---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts"), "Overview"));
        this.documentationsRepository.save(new Documentations("What is Power BI - Service?", "PowerBI Service", List.of("What is the Power BI service?---https://docs.microsoft.com/en-us/power-bi/fundamentals/power-bi-service-overview", " Learn your way around the Power BI service---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-experience","Tutorial: Get started creating in the Power BI service---https://docs.microsoft.com/en-us/power-bi/fundamentals/service-get-started"), "Overview"));
        this.documentationsRepository.save(new Documentations("Get started with Power BI - Service", "PowerBI Service", List.of("Create a report from an Excel file in the Power BI service---https://docs.microsoft.com/en-us/power-bi/create-reports/service-report-create-new?source=recommendations", "Getting around in the Power BI service - Power BI---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-experience"), "Learn"));
        this.documentationsRepository.save(new Documentations("Reports in Power BI - Service", "PowerBI Service", List.of("Reports in Power BI---https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reports", "Create quick reports in the Power BI service---https://docs.microsoft.com/en-us/power-bi/create-reports/service-quick-create-report?source=recommendations", "Basic concepts for designers in the Power BI service---https://docs.microsoft.com/en-us/power-bi/fundamentals/service-basic-concepts?source=recommendations"), "Overview"));
        this.documentationsRepository.save(new Documentations("What is Power BI - Mobile?", "PowerBI Mobile", List.of("Mobile development in Power BI - Power BI---https://docs.microsoft.com/en-us/power-bi/developer/visuals/mobile-development", "What are the mobile apps?---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-for-mobile-devices","What's new in the mobile apps for Power BI?---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-whats-new-in-the-mobile-apps"), "Overview"));
        this.documentationsRepository.save(new Documentations("Get started with Power BI - Mobile", "PowerBI Mobile", List.of("Android devices---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-android-app-get-started", " iOS devices---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-iphone-app-get-started", "Explore dashboards and reports in the Power BI mobile apps---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-quickstart-view-dashboard-report"), "Learn"));
        this.documentationsRepository.save(new Documentations("Reports in Power BI - Mobile", "PowerBI Mobile", List.of("Optimize reports for the mobile apps---https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-create-mobile-optimized-report-about", "Share a dashboard or report from the Power BI mobile apps---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-share-dashboard-from-the-mobile-apps?tabs=classic-look", "Connect with OAuth to on-premises reports---https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-oauth-ssrs"), "Overview"));



        this.courseRepository.save(new Course("Work with Power BI visuals", "PowerBI Desktop", List.of("Data Analyst", "Power Platform", "Intermediate"), 2.7, "1 hr 13 min", LocalDateTime.now(), 44, "Learn how to choose from the exceptional visuals that Power BI makes available to you.", "Intermediate", "IT with strong background/Data Analyst", "xxxxxxx", List.of("Introduction to Power BI visuals---1 min", "Add visualization items to reports---1 min", "Choose an effective visualization---10 min", "Format and configure visualizations---6 min", "Import a custom visual---2 min", "Lab - Design a report in Power BI desktop---45 min", "Summary---2 min"), "Formatting visuals will direct the user’s attention to exactly where you want it, while helping to make the visual easier to read and interpret. You will also learn about how to use key performance indicators (KPIs).In this module, you will: Add visualization items to reports. Choose an effective visualization. Format and configure visualizations. Import a custom visual. Add an R or Python visual." , "None"));
        this.courseRepository.save(new Course("Introduction to Power BI", "PowerBI Desktop", List.of("Business Analyst", "Student", "Beginner"), 4.8, "46 min", LocalDateTime.now(), 166, "Learn how you can leverage Power BI to easily build reports and dashboards with interactive visualizations.", "Beginner", "Everyone (with different background)", "xxxxxxx", List.of("What is Power BI?---10 min", "Data modeling and visualizations---20 min", "Security and administration---15 min", "Customer case study – Miami Heat---7 min", "Import a custom visual---2 min", "Power BI in action---45 min", "Summary---2 min"), "Learn how you can leverage Power BI to easily build reports and dashboards with interactive visualizations and see how other organizations have used this solution to drive business results with actionable insights.In this module, you will: Describe the business value and features of Power BI. See how Power BI works and looks from the user’s perspective." , "None"));
        this.courseRepository.save(new Course("How to build a dashboard", "PowerBI Desktop", List.of("Business Analyst", "Business User", "Beginner"), 5.0, "41 min", LocalDateTime.now(), 54, "This module will teach you how to do all of that without effecting your underlying dataset.", "Beginner", "Everyone (with different background)", "xxxxxxx", List.of("Connect to data---10 min", "Transform data---20 min", "Visualize data---15 min", "Build a dashboard---7 min", "Collaborate and share---2 min", "Summary and resources---2 min"), "We all live in a data culture where business decisions are based on facts, not opinions. We need data to help us make these decisions. Power BI Desktop is a free application for PCs that lets you gather, transform, and visualize your data. Power BI Desktop and the Power BI Service work together. You can create your reports in Power BI Desktop and then publish them to the Power BI Service for others to consume. In this module, you will: Learn to connect to data in Power BI desktop, Transform and model the data you import, Build basic visualizations, Create and share a dashboard, Discover how to collaborate in Power BI" , "None"));
        this.courseRepository.save(new Course("Power BI Mobile apps", "PowerBI Mobile", List.of("Beginner", "Business User", "Data Analyst"), 3.7, "1 hr 29 min", LocalDateTime.now(), 87, "This module provides the information that you need to work effectively with the Power BI mobile apps.", "Beginner", "IT with strong background/Data Analyst", "xxxxxxx", List.of("What are the Power BI Mobile apps?---10 min", "Find your data---20 min", "View and interact with your data---15 min", "Maximize your experience---7 min", "Get your data when you're out in the real world---2 min", "Summary and resources---2 min"), "We all live in a data culture where business decisions are based on facts, not opinions. We need data to help us make these decisions. Power BI Desktop is a free application for PCs that lets you gather, transform, and visualize your data. Power BI Desktop and the Power BI Service work together. You can create your reports in Power BI Desktop and then publish them to the Power BI Service for others to consume. In this module, you will: Learn to connect to data in Power BI desktop, Transform and model the data you import, Build basic visualizations, Create and share a dashboard, Discover how to collaborate in Power BI" , "None"));
        this.courseRepository.save(new Course("Power BI Mobile apps", "PowerBI Mobile", List.of("Beginner", "Business User", "Data Analyst"), 3.7, "1 hr 29 min", LocalDateTime.now(), 87, "This module provides the information that you need to work effectively with the Power BI mobile apps.", "Beginner", "IT with strong background/Data Analyst", "xxxxxxx", List.of("What are the Power BI Mobile apps?---10 min", "Find your data---20 min", "View and interact with your data---15 min", "Maximize your experience---7 min", "Get your data when you're out in the real world---2 min", "Summary and resources---2 min"), "We all live in a data culture where business decisions are based on facts, not opinions. We need data to help us make these decisions. Power BI Desktop is a free application for PCs that lets you gather, transform, and visualize your data. Power BI Desktop and the Power BI Service work together. You can create your reports in Power BI Desktop and then publish them to the Power BI Service for others to consume. In this module, you will: Learn to connect to data in Power BI desktop, Transform and model the data you import, Build basic visualizations, Create and share a dashboard, Discover how to collaborate in Power BI" , "None"));
        this.courseRepository.save(new Course("Power BI Mobile apps", "PowerBI Mobile", List.of("Beginner", "Business User", "Data Analyst"), 3.7, "1 hr 29 min", LocalDateTime.now(), 87, "This module provides the information that you need to work effectively with the Power BI mobile apps.", "Beginner", "IT with strong background/Data Analyst", "xxxxxxx", List.of("What are the Power BI Mobile apps?---10 min", "Find your data---20 min", "View and interact with your data---15 min", "Maximize your experience---7 min", "Get your data when you're out in the real world---2 min", "Summary and resources---2 min"), "We all live in a data culture where business decisions are based on facts, not opinions. We need data to help us make these decisions. Power BI Desktop is a free application for PCs that lets you gather, transform, and visualize your data. Power BI Desktop and the Power BI Service work together. You can create your reports in Power BI Desktop and then publish them to the Power BI Service for others to consume. In this module, you will: Learn to connect to data in Power BI desktop, Transform and model the data you import, Build basic visualizations, Create and share a dashboard, Discover how to collaborate in Power BI" , "None"));
        this.courseRepository.save(new Course("Learn Power BI Service", "PowerBI Service", List.of("Beginner", "Student", "Data Analyst"), 3.2, "3 hr 38 min", LocalDateTime.now(), 87, "This module provides the information that you need to work effectively with the Power BI service", "Beginner", "IT with strong background/Data Analyst", "xxxxxxx", List.of("Introduction---10 min", "Use Power BI Service---20 min", "v---15 min", "Tour and use the Power BI service---7 min", "Summary and resources---2 min"), "Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together." , "None"));
        this.courseRepository.save(new Course("Learn Power BI Service", "PowerBI Service", List.of("Beginner", "Student", "Data Analyst"), 3.2, "3 hr 38 min", LocalDateTime.now(), 87, "This module provides the information that you need to work effectively with the Power BI service", "Beginner", "IT with strong background/Data Analyst", "xxxxxxx", List.of("Introduction---10 min", "Use Power BI Service---20 min", "v---15 min", "Tour and use the Power BI service---7 min", "Summary and resources---2 min"), "Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together." , "None"));
        this.courseRepository.save(new Course("Learn Power BI Service", "PowerBI Service", List.of("Beginner", "Student", "Data Analyst"), 3.2, "3 hr 38 min", LocalDateTime.now(), 87, "This module provides the information that you need to work effectively with the Power BI service", "Beginner", "IT with strong background/Data Analyst", "xxxxxxx", List.of("Introduction---10 min", "Use Power BI Service---20 min", "v---15 min", "Tour and use the Power BI service---7 min", "Summary and resources---2 min"), "Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together.Explore how Power BI can make your business more efficient.Learn how to create compelling visuals and reports.Learn what Power BI is, including its building blocks and how they work together.In this module, you will:Learn how Power BI services and applications work together." , "None"));

        this.learningPathRepository.save(new LearningPath("Introduction to Power BI", List.of(this.courseRepository.findById(2L).get(), this.courseRepository.findById(4L).get(), this.courseRepository.findById(9L).get())));
        this.learningPathRepository.save(new LearningPath("Prepare data for analysis", List.of(this.courseRepository.findById(1L).get(), this.courseRepository.findById(3L).get(), this.courseRepository.findById(7L).get())));

        this.questionRepository.save(new Question("You are interested in creating a measure that will always calculate the total sales for 2020, irrespective of the year selected in any other visual in Power BI. Which of the following is the right way to create such a measure?", List.of("Total Sales for 2020= CALCULATE(SUM(‘Sales OrderDetails'[Total Price]), YEAR(‘Sales OrderDetails'[orderdate]) = 2020)", "Total Sales for 2020= SUM(CALCULATE(‘Sales OrderDetails'[Total Price]), YEAR(‘Sales OrderDetails'[orderdate]) = 2020)", "Total Sales for 2020= TOTAL(SUM(‘Sales OrderDetails'[Total Price]), YEAR(‘Sales OrderDetails'[orderdate]) = 2020)", "It is not possible to create such a measure."), 1));
        this.questionRepository.save(new Question("The data model has an impact on the time consumed in the refreshing of a model but once the model is loaded in the memory, it has no impact on the performance of the reports. Select whether the statement is True/False.", List.of("True", "False"), 2));
        this.questionRepository.save(new Question("What will be the result of the following DAX formula if the year 2020 is chosen on a slicer of a report? 2019 Salary_Cost = CALCULATE([Total Salary_cost], Filter (Date, Date[Year]=2019))", List.of("Salary_cost for the Year 2020 as Slicer Selection overrides DAX Filter.", "Salary_cost for the Year 2019 as DAX Filter overrides Slicer Selection.", "Blank. It will return no records.", "It will return Salary_cost records for the year 2019 as well as 2020."), 3));
        this.questionRepository.save(new Question("Which of the following is the right DAX function to modify a single directional relationship to a bi-directional relationship on the fly (within the measure)?", List.of("TREATAS", "USERELATIONSHIP", "CROSSFILTER", "RELATEDTABLE", "RELATED"), 3));
        this.questionRepository.save(new Question("What is the use of Row Level Security (RLS) in Power BI?", List.of("Assigning the security permissions for the underlying Power BI Azure SQL Database", "Adding the ability to link Power BI Log-in to organizational Active Directory or Window Login through Single Sign On (SSO)", "Restricting data access for the given users ( By assigning users to roles)", "Restrictions to specific measures within Power BI reports to some specific users", "All the above"), 3));
        this.questionRepository.save(new Question("Consider that you want to split your query into two parts. Which of the following options would you use in Power BI?", List.of("Format Query", "Split Query", "Extract previous", "Mark Query"), 3));
        this.questionRepository.save(new Question("Consider the statement.Row Level Security can’t be applied in Power BI Desktop while connecting via a Live connection to Analysis Services, these need to be set within the AS model.", List.of("True", "False"), 2));

        this.examRepository.save(new Exam("Microsoft Power BI PL-300 (DA-100) Certification","PowerBI Desktop", 3.6, "30 min", LocalDateTime.now(), 141, "This PL-300(earlier named as DA-100) Certification Exam: Microsoft Power BI  Data Analyst certification is for data analysts. ", "This PL-300(earlier named as DA-100) Certification Exam: Microsoft Power BI  Data Analyst certification is for data analysts. This certificate is crucial for you if you use Power BI to create data visualizations. The DA-100 course teaches you to design scalable data models, clean and transform data and present analytic insights. This set of 25 DA 100 exam questions will cover the important skills measured in the DA-100 Exam such as:Prepare the data. Create a model. Create Visualization. Analyze and prepare insights. Deploy and maintain deliverables. These DA 100 exam questions will give you a very good idea of how the actual exam would look like; you can practice more with our DA-100 practice exam." ,List.of("Watch PL-300 Exam Prep videos on Learn", "Download the PL-300 study guide to help you prepare for the exam", "Demo the exam experience by visiting our Exam Sandbox"), "Intermediate", "Microsoft Power BI  Data Analyst", List.of(this.questionRepository.findById(1L).get(),this.questionRepository.findById(2L).get(),this.questionRepository.findById(3L).get(),this.questionRepository.findById(4L).get(),this.questionRepository.findById(5L).get(),this.questionRepository.findById(6L).get(),this.questionRepository.findById(7L).get())));

    }
}
